// Templates types
export const FETCHING_TEMPLATES = "FETCHING_TEMPLATES";
export const FETCHING_TEMPLATES_SUCCESS = "FETCHING_TEMPLATES_SUCCESS";
export const FETCHING_TEMPLATES_FAILED = "FETCHING_TEMPLATES_FAILED";

// User types
export const FETCHING_USER = "FETCHING_USER";
export const FETCHING_USER_SUCCESS = "FETCHING_USER_SUCCESS";
export const FETCHING_USER_FAILED = "FETCHING_USER_FAILED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Error types
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
